### ISSUE TITLE
Unit tests execution fails when run on travis

### ISSUE THREAD

**Issue by doubleface** [cozy/cozy-konnector-libs#35]
https://travis-ci.org/cozy/cozy-konnector-libs/builds/280295435?utm_source=github_status&utm_medium=notification

And it runs well in a local environment. It seems there is a problem with dates.

**Comment by ptbrowne** [comment]
I'll check this

**Comment by ptbrowne** [comment]
Done in https://github.com/cozy/cozy-konnector-libs/commit/b106615ae6600a13665bf760e7dd3c8684ac39e4
