### ISSUE TITLE
Warning when using with webpack

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-konnector-libs#56]
When importing `cozy-konnector-libs`, we have a warning : 

```
WARNING in ./node_modules/cozy-konnector-libs/node_modules/colors/lib/extendStringPrototype.js
101:31-45 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/cozy-konnector-libs/node_modules/colors/lib/extendStringPrototype.js
 @ ./node_modules/cozy-konnector-libs/node_modules/colors/lib/index.js
 @ ./node_modules/cozy-konnector-libs/libs/log-formats.js
 @ ./node_modules/cozy-konnector-libs/libs/logger.js
 @ ./node_modules/cozy-konnector-libs/index.js
 @ ./src/targets/services/notifications.js
```

This is because `colors` is using a dynamic require in its setTheme function. `colors` has not been updated in 3 years. I think it would be better to switch to `chalk` since it is more maintained and does not have this problem.

Related : 
Issue on colors : https://github.com/Marak/colors.js/issues/137
People switching to chalk because of it : https://github.com/ctrlplusb/react-universally/pull/210

EDIT : 

https://github.com/cozy/cozy-konnector-libs/blob/master/helpers/init-konnector-config.js#L13 is also causing a problem. This is related to the splitting of cozy-konnector-libs into pure library function and a CLI.

**Comment by doubleface** [comment]
Ok ! Here is the PR : https://github.com/cozy/cozy-konnector-libs/pull/58
