### ISSUE TITLE
Split between CLI and library functions

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-konnector-libs#59]
We should split pure library functions and CLI functionality. This is for performance reasons as the CLI is importing libraries that users of cozy-konnector-libs only for library functions do not no need. It also causes a webpack problem since the CLI needs to import a custom config file here : https://github.com/cozy/cozy-konnector-libs/blob/master/helpers/init-konnector-config.js#L13

**Comment by doubleface** [comment]
There is also a need to split the tools also used by services : ex the logger.
A service should not need to include cozy-konnector-libs just to be able to log inforamtions to the stack.

**Comment by doubleface** [comment]
Also, to my view, the logger should only log JSON (production mode) and it should be the role of cozy-konnector-dev and cozy-konnector-standalone to parse logs and display them appropriately.

It will allow to have a logger independent from the environment

**Comment by ptbrowne** [comment]
Why, I guess it is sensible for the logger to log differently according to the process.env.NODE_ENV variable ?
