### ISSUE TITLE
standalone should take whether to record/replay in parameter

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-konnector-libs#96]
We have 3 lines where we could have one.

https://github.com/konnectors/cozy-konnector-maif/pull/33#discussion_r169265544

> This could maybe go directly in the standalone command instead of needing to set several scripts in each repo.

```
cozy-konnector-standalone src/index.js record
cozy-konnector-standalone src/index.js replay
```

**Comment by doubleface** [comment]
Ok, I just would prefer : 

```
cozy-konnector-standalone src/index.js --record
cozy-konnector-standalone src/index.js --replay
```

To not be dependent of the parameters order.

**Comment by ptbrowne** [comment]
I agree.

**Comment by ptbrowne** [comment]
I agree
